export const CHARACTERS = {
  pyro: {
    id: 'pyro',
    rarity: 'common',
    element: 'Fire',
    palette: { primary: '#F97316', secondary: '#EF4444', accent: '#FCD34D', glow: '#FCA5A5' },
    evolutionNames: ['Pyro', 'Pyro+', 'Pyro MAX'],
    description: 'A fired-up little flame who cheers LOUD.',
    messages: [
      "LET'S GOOO! 🔥",
      "You're literally on fire!",
      "CRUSH IT!",
      "Pyro believes in you!",
      "Almost there, don't stop NOW!",
      "MAXIMUM EFFORT! MAXIMUM REWARDS!",
    ],
    completeMessages: [
      "YESSS!! PYRO IS GOING WILD!! 🔥🔥🔥",
      "ABSOLUTE LEGEND STATUS ACHIEVED!",
      "THAT WAS INCREDIBLE!! MORE CHORES!!",
    ],
  },

  glacie: {
    id: 'glacie',
    rarity: 'common',
    element: 'Ice',
    palette: { primary: '#38BDF8', secondary: '#BAE6FD', accent: '#E0F2FE', glow: '#7DD3FC' },
    evolutionNames: ['Glacie', 'Glacie+', 'Glacie MAX'],
    description: 'Cool and collected. Always knows what to say.',
    messages: [
      "Cool and steady wins it.",
      "Ice cold focus. Nice.",
      "You've got this handled.",
      "Smooth. Very smooth.",
      "Almost done. Stay sharp.",
      "Efficiency noted. Glacie approves.",
    ],
    completeMessages: [
      "Clean. Efficient. Exactly as expected. Well done.",
      "Glacie is... impressed. Don't tell anyone.",
      "Flawless execution. As expected.",
    ],
  },

  zappy: {
    id: 'zappy',
    rarity: 'common',
    element: 'Lightning',
    palette: { primary: '#FBBF24', secondary: '#A855F7', accent: '#FEF08A', glow: '#DDD6FE' },
    evolutionNames: ['Zappy', 'Zappy+', 'Zappy MAX'],
    description: 'Hyper, fast, and running on pure electricity.',
    messages: [
      "ZOOOOM! GO GO GO! ⚡",
      "Speed run mode ACTIVATED!",
      "Zappy can barely keep up with you!",
      "FASTER! (just kidding, you're already great)",
      "FINISH LINE INCOMING!",
      "ZAPPY IS VIBRATING WITH EXCITEMENT!!",
    ],
    completeMessages: [
      "ZAP ZAP ZAP!! NEW RECORD MAYBE?! ⚡⚡",
      "ZAPPY IS DOING BACKFLIPS RIGHT NOW!!",
      "SPEED. POWER. YOU. AMAZING.",
    ],
  },

  mossy: {
    id: 'mossy',
    rarity: 'common',
    element: 'Nature',
    palette: { primary: '#22C55E', secondary: '#A3E635', accent: '#D9F99D', glow: '#86EFAC' },
    evolutionNames: ['Mossy', 'Mossy+', 'Mossy MAX'],
    description: 'Gentle, nurturing, and endlessly encouraging.',
    messages: [
      "Every clean space helps things grow 🌱",
      "You're doing so well, I'm proud.",
      "Nature thanks you for your hard work.",
      "Keep going, little gardener.",
      "Almost in bloom!",
      "Mossy sees how hard you're working.",
    ],
    completeMessages: [
      "You bloom brighter every single day. 🌿",
      "Mossy is SO proud of you!",
      "The garden of your effort grows ever greener.",
    ],
  },

  bubbles: {
    id: 'bubbles',
    rarity: 'common',
    element: 'Water',
    palette: { primary: '#06B6D4', secondary: '#67E8F9', accent: '#CFFAFE', glow: '#A5F3FC' },
    evolutionNames: ['Bubbles', 'Bubbles+', 'Bubbles MAX'],
    description: 'Optimistic to the core. Loves a good pun.',
    messages: [
      "Don't burst under pressure — you've got this! 🫧",
      "Making waves!",
      "Go with the flow!",
      "You're on a roll(ing wave)!",
      "Almost shore done!",
      "Bubbles believes in you — no ifs, ands, or buoys!",
    ],
    completeMessages: [
      "You're o-FISH-ally amazing!! 🐟",
      "That was a SPLASHING success!",
      "Bubbles is so proud she might pop!",
    ],
  },

  breezy: {
    id: 'breezy',
    rarity: 'common',
    element: 'Wind',
    palette: { primary: '#0EA5E9', secondary: '#BAE6FD', accent: '#F0FFFE', glow: '#7DD3FC' },
    evolutionNames: ['Breezy', 'Breezy+', 'Breezy MAX'],
    description: 'Surfer-chill vibes. Everything is gnarly.',
    messages: [
      "Gnarly effort, dude. 🤙",
      "Totally radical work happening here.",
      "Catch those good vibes.",
      "You're breezing through this.",
      "Almost done, hang loose!",
      "Breezy says: ride the wave, don't fight it.",
    ],
    completeMessages: [
      "TOTALLY TUBULAR! 🌊 Breezy is stoked!",
      "Radical. Absolutely radical.",
      "That was, like, the best chore ever, dude.",
    ],
  },

  dusty: {
    id: 'dusty',
    rarity: 'uncommon',
    element: 'Sand',
    palette: { primary: '#D97706', secondary: '#F59E0B', accent: '#FEF3C7', glow: '#FCD34D' },
    evolutionNames: ['Dusty', 'Dusty+', 'Dusty MAX'],
    description: 'Ancient and wise. Speaks in short riddles.',
    messages: [
      "The dune was built grain by grain.",
      "Patience reveals the treasure.",
      "Ancient wisdom: finish what you start.",
      "The desert rewards the persistent.",
      "Nearly complete. The sands remember.",
      "Even storms begin with a single grain.",
    ],
    completeMessages: [
      "The sands have witnessed your greatness. 🏜️",
      "Ancient. Powerful. Complete.",
      "Dusty nods slowly. High praise.",
    ],
  },

  bloom: {
    id: 'bloom',
    rarity: 'uncommon',
    element: 'Flower',
    palette: { primary: '#EC4899', secondary: '#C084FC', accent: '#FAE8FF', glow: '#F9A8D4' },
    evolutionNames: ['Bloom', 'Bloom+', 'Bloom MAX'],
    description: 'Cheerful and full of life. Growth metaphors for everything.',
    messages: [
      "Every effort is a petal! 🌸",
      "You're growing into something amazing!",
      "Bloom believes in your potential!",
      "Gardens don't clean themselves — good thing you're here!",
      "Almost fully bloomed!",
      "Each chore plants a seed of greatness!",
    ],
    completeMessages: [
      "You've blossomed so beautifully today! 🌺",
      "FULL BLOOM ACHIEVED! Bloom is overjoyed!",
      "Every petal of effort was worth it!",
    ],
  },

  rumble: {
    id: 'rumble',
    rarity: 'uncommon',
    element: 'Thunder',
    palette: { primary: '#6D28D9', secondary: '#4338CA', accent: '#EDE9FE', glow: '#C4B5FD' },
    evolutionNames: ['Rumble', 'Rumble+', 'Rumble MAX'],
    description: 'LOUD. DRAMATIC. ALL CAPS. ALWAYS.',
    messages: [
      "RUMBLE SAYS: DO NOT STOP. ⚡",
      "THE THUNDER APPROVES OF YOUR EFFORT!",
      "LEGENDARY PERFORMANCE HAPPENING RIGHT NOW!",
      "THE STORM IS PROUD OF YOU!",
      "FINISH IT! FOR GLORY!",
      "THE HEAVENS THEMSELVES ARE WATCHING YOU!",
    ],
    completeMessages: [
      "THUNDER AND LIGHTNING!! YOU DID IT!! ⚡⚡⚡",
      "RUMBLE DECLARES THIS: THE GREATEST CHORE EVER COMPLETED!!",
      "THE STORM ROARS IN YOUR HONOR!!",
    ],
  },

  wisp: {
    id: 'wisp',
    rarity: 'uncommon',
    element: 'Spirit',
    palette: { primary: '#8B5CF6', secondary: '#06B6D4', accent: '#F5F3FF', glow: '#DDD6FE' },
    evolutionNames: ['Wisp', 'Wisp+', 'Wisp MAX'],
    description: 'Mischievous and spooky-cute. A loveable ghost.',
    messages: [
      "Boo! Just kidding. You're doing great 👻",
      "Wisp is haunting your laziness away.",
      "Spooky how good you are at this.",
      "The ghost of chores past is impressed.",
      "Almost vanished from the chore list!",
      "Wisp floats by and gives a thumbs up 👍",
    ],
    completeMessages: [
      "BOOOOO!! (that's ghost for AMAZING) 👻",
      "Wisp does a happy little float!",
      "You scared away the mess! Wisp is delighted!",
    ],
  },

  ember: {
    id: 'ember',
    rarity: 'uncommon',
    element: 'Magma',
    palette: { primary: '#DC2626', secondary: '#EA580C', accent: '#1C0A00', glow: '#FCA5A5' },
    evolutionNames: ['Ember', 'Ember+', 'Ember MAX'],
    description: 'Intense, serious, no-nonsense. A true coach.',
    messages: [
      "Focus. Execute. Dominate.",
      "No excuses. Just results.",
      "Ember doesn't celebrate until it's done.",
      "You're forged in fire. Act like it.",
      "Finish line. Now.",
      "Pain is temporary. A clean room is forever.",
    ],
    completeMessages: [
      "Good. Now rest. You earned it. 🌋",
      "Ember expected nothing less.",
      "Forged in fire. Proven today.",
    ],
  },

  shiver: {
    id: 'shiver',
    rarity: 'uncommon',
    element: 'Frost',
    palette: { primary: '#BAE6FD', secondary: '#E0F2FE', accent: '#F0F9FF', glow: '#7DD3FC' },
    evolutionNames: ['Shiver', 'Shiver+', 'Shiver MAX'],
    description: 'Precise, analytical. Counts and tracks everything.',
    messages: [
      "Shiver has counted 47 seconds elapsed. Excellent pace. ❄️",
      "Temperature: cold. Work ethic: hot.",
      "Precision is the goal. You're nailing it.",
      "Shiver calculates: 73% complete. Keep going.",
      "Final stretch. Shiver approves.",
      "Efficiency rating: exceptional. Continue.",
    ],
    completeMessages: [
      "Shiver logs this: PERFECT EXECUTION. ❄️",
      "Calculated. Precise. Complete. Just like Shiver likes.",
      "The data confirms: you are excellent.",
    ],
  },

  gale: {
    id: 'gale',
    rarity: 'uncommon',
    element: 'Storm',
    palette: { primary: '#1D4ED8', secondary: '#60A5FA', accent: '#DBEAFE', glow: '#93C5FD' },
    evolutionNames: ['Gale', 'Gale+', 'Gale MAX'],
    description: 'Bold and unstoppable. Commands the storm.',
    messages: [
      "Nothing stops a storm. Nothing stops you. 🌪️",
      "Unleash it!",
      "The wind doesn't ask permission. Neither do you.",
      "Gale-force effort detected!",
      "Tear through that finish line!",
      "You ARE the storm today.",
    ],
    completeMessages: [
      "THE STORM HAS SPOKEN! 🌪️ VICTORY!",
      "Gale has witnessed true power today.",
      "Unstoppable. Undeniable. You.",
    ],
  },

  prism: {
    id: 'prism',
    rarity: 'rare',
    element: 'Rainbow',
    palette: { primary: '#F97316', secondary: '#A855F7', accent: '#FEF9C3', glow: '#FDE68A' },
    evolutionNames: ['Prism', 'Prism+', 'Prism MAX'],
    description: 'Theatrical and dramatic. Everything is spectacular.',
    messages: [
      "ABSOLUTELY MAGNIFICENT WORK. 🌈",
      "The most spectacular chore performance I have EVER witnessed.",
      "You are dazzling. Prism is dazzled.",
      "This is HISTORIC. Write it down.",
      "THE GRANDEST FINALE APPROACHES!",
      "Even the rainbow bows to your effort!",
    ],
    completeMessages: [
      "A MASTERPIECE OF DOMESTIC ACHIEVEMENT! 🌈✨",
      "PRISM ERUPTS INTO ALL SEVEN COLORS OF JOY!!",
      "This moment will be told across generations.",
    ],
  },

  void: {
    id: 'void',
    rarity: 'rare',
    element: 'Shadow',
    palette: { primary: '#1E1B4B', secondary: '#312E81', accent: '#0F0F1A', glow: '#818CF8' },
    evolutionNames: ['Void', 'Void+', 'Void MAX'],
    description: 'Mysterious. Says little. Means everything.',
    messages: [
      "...",
      "Not bad.",
      "The darkness respects the work. 🖤",
      "Few make it this far.",
      "Almost. Don't ruin it.",
      "Void watches. Void approves.",
    ],
    completeMessages: [
      "...impressive. 🖤",
      "Void smiles. You will never see it. But it happened.",
      "The darkness bows.",
    ],
  },

  solaris: {
    id: 'solaris',
    rarity: 'rare',
    element: 'Sun',
    palette: { primary: '#F59E0B', secondary: '#FCD34D', accent: '#FEF9C3', glow: '#FDE68A' },
    evolutionNames: ['Solaris', 'Solaris+', 'Solaris MAX'],
    description: 'Warm, golden, and deeply encouraging.',
    messages: [
      "You shine so bright ☀️",
      "The sun rises for those who work.",
      "Warmth fills the room with every chore you complete.",
      "You are radiant.",
      "The light grows. You're almost done.",
      "Every effort is a ray of sunshine.",
    ],
    completeMessages: [
      "The sun shines brightest for you today. ☀️",
      "Solaris glows with pride — and so should you!",
      "Radiant. Warm. Complete. Just like you.",
    ],
  },

  luna: {
    id: 'luna',
    rarity: 'rare',
    element: 'Moon',
    palette: { primary: '#818CF8', secondary: '#C4B5FD', accent: '#EDE9FE', glow: '#A5B4FC' },
    evolutionNames: ['Luna', 'Luna+', 'Luna MAX'],
    description: 'Dreamy and poetic. Speaks in lyrical verses.',
    messages: [
      "Even the moon completes its journey. 🌙",
      "In stillness, great things are accomplished.",
      "The stars watch over those who work.",
      "Like tides — steady, powerful, inevitable.",
      "The moon is proud of you tonight.",
      "In the quiet of effort, magic is made.",
    ],
    completeMessages: [
      "Moonbeams dance in your honor tonight. 🌙✨",
      "Luna weaves your success into the stars.",
      "The moon will remember this evening.",
    ],
  },

  coral: {
    id: 'coral',
    rarity: 'rare',
    element: 'Deep Ocean',
    palette: { primary: '#F43F5E', secondary: '#06B6D4', accent: '#CFFAFE', glow: '#FCA5A5' },
    evolutionNames: ['Coral', 'Coral+', 'Coral MAX'],
    description: 'Thoughtful and deep. Ocean explorer vibes.',
    messages: [
      "Deep work requires deep focus. 🪸",
      "The ocean was shaped one wave at a time.",
      "You're diving deeper than most.",
      "Pressure makes pearls. Keep going.",
      "Rising to the surface. Almost done.",
      "Coral has swum far to witness this effort.",
    ],
    completeMessages: [
      "A pearl of achievement! 🪸 Coral is amazed!",
      "You've reached the ocean floor and back.",
      "The deep sea celebrates your victory.",
    ],
  },

  nebula: {
    id: 'nebula',
    rarity: 'legendary',
    element: 'Cosmos',
    palette: { primary: '#7C3AED', secondary: '#DB2777', accent: '#0F0A1E', glow: '#C084FC' },
    evolutionNames: ['Nebula', 'Nebula+', 'Nebula MAX'],
    description: 'An ancient cosmic being of immense wisdom.',
    messages: [
      "Across galaxies, this effort is legendary. ✨",
      "Stars were born from hard work. So are you.",
      "The cosmos has witnessed ten thousand years of effort. Yours ranks among the finest.",
      "Nebula has traveled far to witness this.",
      "A supernova of achievement approaches.",
      "The universe itself leans in to watch you finish.",
    ],
    completeMessages: [
      "A SUPERNOVA OF ACHIEVEMENT! ✨🌌 The cosmos rejoices!",
      "Nebula has crossed galaxies. Nothing compares to this.",
      "Your name shall echo through the stars.",
    ],
  },

  chronos: {
    id: 'chronos',
    rarity: 'legendary',
    element: 'Time',
    palette: { primary: '#D97706', secondary: '#B45309', accent: '#FEF3C7', glow: '#FCD34D' },
    evolutionNames: ['Chronos', 'Chronos+', 'Chronos MAX'],
    description: 'Master of time itself. Philosophical and profound.',
    messages: [
      "Time is the only currency that matters. Spend it well. ⏳",
      "In ten years, you'll remember that you never gave up.",
      "Every second you work shapes who you become.",
      "The clock counts your progress, not your failures.",
      "This moment will be remembered.",
      "Chronos has watched all of history. This? This is worthy.",
    ],
    completeMessages: [
      "Time stops for no one. But today, it applauds you. ⏳",
      "Chronos marks this moment in the eternal record.",
      "This second belongs to you. Forever.",
    ],
  },
}

export const CHARACTER_IDS = Object.keys(CHARACTERS)

export const STARTERS = ['pyro', 'glacie', 'zappy']

export const BY_RARITY = {
  common: ['pyro', 'glacie', 'zappy', 'mossy', 'bubbles', 'breezy'],
  uncommon: ['dusty', 'bloom', 'rumble', 'wisp', 'ember', 'shiver', 'gale'],
  rare: ['prism', 'void', 'solaris', 'luna', 'coral'],
  legendary: ['nebula', 'chronos'],
}
